// <auto-generated />
namespace Proyecto_BazarLibreria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Datos_Bazar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datos_Bazar));
        
        string IMigrationMetadata.Id
        {
            get { return "202411241507018_Datos_Bazar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
